import type { VuetifyOptions } from 'vuetify'
import { resolveVuetifyTheme } from '@core/utils/vuetify'
import { themeConfig } from '@themeConfig'

export const staticPrimaryColor = '#ef6b1f'

const theme: VuetifyOptions['theme'] = {
  defaultTheme: resolveVuetifyTheme(),
  themes: {
    light: {
      dark: false,
      colors: {
        'green-sunstack': '#26a17e',
        'green-sunstack-darker': '#d95f1b',
        'yellow-sunstack': '#f7bb16',
        'grey-sunstack': '#ededed',
        'on-grey-sunstack': '#252525',
        primary: localStorage.getItem(`${themeConfig.app.title}-lightThemePrimaryColor`) || staticPrimaryColor,
        'on-primary': '#fff',
        secondary: '#5b6b7a',
        'on-secondary': '#fff',
        success: '#2fbf71',
        'on-success': '#fff',
        info: '#2a7fdb',
        'on-info': '#fff',
        warning: '#f0b23d',
        'on-warning': '#2a211b',
        error: '#e5473a',
        background: '#fbf7f2',
        'on-background': '#2c231c',
        surface: '#fff',
        'on-surface': '#2c231c',
        'grey-50': '#fcfaf7',
        'grey-100': '#f4eee7',
        'grey-200': '#e7dfd6',
        'grey-300': '#d9d0c5',
        'grey-400': '#b7ada1',
        'grey-500': '#9b8f83',
        'grey-600': '#7f7469',
        'grey-700': '#665b51',
        'grey-800': '#4e443b',
        'grey-900': '#342c25',
        'perfect-scrollbar-thumb': '#d6ccc2',
        'skin-bordered-background': '#fff',
        'skin-bordered-surface': '#fff',
        purple: '#8b6ad6',
        'on-purple': '#f2eefc',
      },

      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#4C4E64',
        'tooltip-background': '#4A5072',
        'overlay-scrim-opacity': 0.5,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.5,
        'border-color': '#2F2B3D',
        'border-opacity': 0.16,
        'high-emphasis-opacity': 1,
        'medium-emphasis-opacity': 0.7,
        'switch-opacity': 0.2,
        'switch-disabled-track-opacity': 0.3,
        'switch-disabled-thumb-opacity': 0.4,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#2F2B3D',
      },
    },
    dark: {
      dark: true,
      colors: {
        'green-sunstack': '#26a17e',
        'green-sunstack-darker': '#d95f1b',
        'yellow-sunstack': '#f7bb16',
        'grey-sunstack': '#ededed',
        'on-grey-sunstack': '#252525',
        primary: localStorage.getItem(`${themeConfig.app.title}-darkThemePrimaryColor`) || staticPrimaryColor,
        'on-primary': '#fff',
        secondary: '#8aa0b3',
        'on-secondary': '#101820',
        success: '#39c87a',
        'on-success': '#0f1b18',
        info: '#4aa3ff',
        'on-info': '#0f1b18',
        warning: '#f1b559',
        'on-warning': '#2a211b',
        error: '#f06d5a',
        background: '#1c1916',
        'on-background': '#f0e7de',
        surface: '#26221f',
        'on-surface': '#f0e7de',
        'grey-50': '#24201d',
        'grey-100': '#2e2925',
        'grey-200': '#3b342f',
        'grey-300': '#4a423c',
        'grey-400': '#5d544d',
        'grey-500': '#746a62',
        'grey-600': '#8e8379',
        'grey-700': '#a59a8f',
        'grey-800': '#c1b6aa',
        'grey-900': '#e0d6cb',
        'perfect-scrollbar-thumb': '#4a423c',
        'skin-bordered-background': '#26221f',
        'skin-bordered-surface': '#26221f',
        purple: '#8b6ad6',
        'on-purple': '#f2eefc',
      },
      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#101121',
        'tooltip-background': '#5E6692',
        'overlay-scrim-opacity': 0.6,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.5,
        'border-color': '#D0D4F1',
        'border-opacity': 0.16,
        'high-emphasis-opacity': 1,
        'medium-emphasis-opacity': 0.7,
        'switch-opacity': 0.4,
        'switch-disabled-track-opacity': 0.4,
        'switch-disabled-thumb-opacity': 0.8,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#0F1422',
        'shadow-key-umbra-opacity': 'rgba(20, 21, 33, 0.06)',
        'shadow-key-penumbra-opacity': 'rgba(20, 21, 33, 0.04)',
        'shadow-key-ambient-opacity': 'rgba(20, 21, 33, 0.02)',
      },
    },
  },
}

export default theme
