import type { VuetifyOptions } from 'vuetify'
import { resolveVuetifyTheme } from '@core/utils/vuetify'
import { themeConfig } from '@themeConfig'

export const staticPrimaryColor = '#26a17e'

const theme: VuetifyOptions['theme'] = {
  defaultTheme: resolveVuetifyTheme(),
  themes: {
    light: {
      dark: false,
      colors: {
        'green-sunstack': '#26a17e',
        'green-sunstack-darker': '#257e63',
        'yellow-sunstack': '#f7bb16',
        'grey-sunstack': '#ededed',
        'on-grey-sunstack': '#252525',
        primary: localStorage.getItem(`${themeConfig.app.title}-lightThemePrimaryColor`) || staticPrimaryColor,
        'on-primary': '#fff',
        secondary: '#8592a3',
        'on-secondary': '#fff',
        success: '#71dd37',
        'on-success': '#fff',
        info: '#03c3ec',
        'on-info': '#fff',
        warning: '#ffab00',
        'on-warning': '#fff',
        error: '#ff3e1d',
        background: '#f5f5f9',
        'on-background': '#32475c',
        surface: '#fff',
        'on-surface': '#32475c',
        'grey-50': '#fafafa',
        'grey-100': '#ebeef0',
        'grey-200': '#eee',
        'grey-300': '#e0e0e0',
        'grey-400': '#bdbdbd',
        'grey-500': '#9e9e9e',
        'grey-600': '#757575',
        'grey-700': '#616161',
        'grey-800': '#424242',
        'grey-900': '#212121',
        'perfect-scrollbar-thumb': '#dbdade',
        'skin-bordered-background': '#fff',
        'skin-bordered-surface': '#fff',
        purple: '#9155FD',
        'on-purple': '#ececec',
      },

      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#4C4E64',
        'tooltip-background': '#4A5072',
        'overlay-scrim-opacity': 0.5,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.5,
        'border-color': '#2F2B3D',
        'border-opacity': 0.16,
        'high-emphasis-opacity': 1,
        'medium-emphasis-opacity': 0.7,
        'switch-opacity': 0.2,
        'switch-disabled-track-opacity': 0.3,
        'switch-disabled-thumb-opacity': 0.4,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#2F2B3D',
      },
    },
    dark: {
      dark: true,
      colors: {
        'green-sunstack': '#26a17e',
        'green-sunstack-darker': '#257e63',
        'yellow-sunstack': '#f7bb16',
        'grey-sunstack': '#ededed',
        'on-grey-sunstack': '#252525',
        primary: localStorage.getItem(`${themeConfig.app.title}-darkThemePrimaryColor`) || staticPrimaryColor,
        'on-primary': '#fff',
        secondary: '#8592a3',
        'on-secondary': '#fff',
        success: '#71dd37',
        'on-success': '#fff',
        info: '#03c3ec',
        'on-info': '#fff',
        warning: '#ffab00',
        'on-warning': '#fff',
        error: '#ff3e1d',
        background: '#232333',
        'on-background': '#dbdbeb',
        surface: '#2b2c40',
        'on-surface': '#dbdbeb',
        'grey-50': '#2a2e42',
        'grey-100': '#444463',
        'grey-200': '#4a5072',
        'grey-300': '#5e6692',
        'grey-400': '#7983bb',
        'grey-500': '#8692d0',
        'grey-600': '#aab3de',
        'grey-700': '#b6bee3',
        'grey-800': '#cfd3ec',
        'grey-900': '#e7e9f6',
        'perfect-scrollbar-thumb': '#4a5072',
        'skin-bordered-background': '#2b2c40',
        'skin-bordered-surface': '#2b2c40',
        purple: '#9155FD',
        'on-purple': '#ececec',
      },
      variables: {
        'code-color': '#d400ff',
        'overlay-scrim-background': '#101121',
        'tooltip-background': '#5E6692',
        'overlay-scrim-opacity': 0.6,
        'hover-opacity': 0.04,
        'focus-opacity': 0.12,
        'selected-opacity': 0.06,
        'activated-opacity': 0.16,
        'pressed-opacity': 0.14,
        'dragged-opacity': 0.1,
        'disabled-opacity': 0.5,
        'border-color': '#D0D4F1',
        'border-opacity': 0.16,
        'high-emphasis-opacity': 1,
        'medium-emphasis-opacity': 0.7,
        'switch-opacity': 0.4,
        'switch-disabled-track-opacity': 0.4,
        'switch-disabled-thumb-opacity': 0.8,
        'switch-checked-disabled-opacity': 0.3,

        // Shadows
        'shadow-key-umbra-color': '#0F1422',
        'shadow-key-umbra-opacity': 'rgba(20, 21, 33, 0.06)',
        'shadow-key-penumbra-opacity': 'rgba(20, 21, 33, 0.04)',
        'shadow-key-ambient-opacity': 'rgba(20, 21, 33, 0.02)',
      },
    },
  },
}

export default theme
